### ISSUE TITLE
Why sanity not syncing up with Medusa on creation of product ? 

### ISSUE THREAD

**Issue by whiletrueee** [abmenzel/medusa-plugin-sanity#2]
## ✅ My sanity studio is running perfectly fine.

![image](https://github.com/abmenzel/medusa-plugin-sanity/assets/73738347/dd9e3db5-7c74-44a6-a806-212b142a5114)

## ✅ Medusa Admin is running perfectly fine.

![image](https://github.com/abmenzel/medusa-plugin-sanity/assets/73738347/8c2ae65b-8552-4e69-a6de-996ca44ad824)

### receiving this on medusa backend log 

![image](https://github.com/abmenzel/medusa-plugin-sanity/assets/73738347/2e68c7ff-00df-451a-863d-86a89de98f26)

**Comment by abmenzel** [comment]
@whiletrueee did you resolve the issue since you closed it?

**Comment by whiletrueee** [comment]
> @whiletrueee did you resolve the issue since you closed it?

yess @abmenzel basically i had some local issues, restarting the admin server worked for me and it started syncing the products

**Comment by abmenzel** [comment]
Glad to hear it! :)
